[profile.default]
src = "src"
out = "out"
libs = ["lib"]

rpc_endpoint = { sepolia-eth = "https://eth-sepolia.g.alchemy.com/v2/7k_wG9g3utYP-js4Bu3vP6cjI_e3VoDj", linea-sepolia = "https://linea-sepolia.g.alchemy.com/v2/7k_wG9g3utYP-js4Bu3vP6cjI_e3VoDj" }

remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@ccip/contracts/=lib/ccip/contracts",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
